apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudwatch-agent-role

rules:
- apiGroups: [""]
  resources:
    - configmaps
    - nodes
    - nodes/proxy
    - pods
    - services
    - endpoints
    - persistentvolumes
    - persistentvolumeclaims
  verbs:
    - get
    - list
    - watch

- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - daemonsets
    - statefulsets
  verbs:
    - get
    - list
    - watch

- apiGroups: ["batch"]
  resources:
    - jobs
  verbs:
    - get
    - list
    - watch

- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch

- apiGroups: ["discovery.k8s.io"]
  resources:
    - endpointslices
  verbs:
    - get
    - list
    - watch
- apiGroups: [""]
  resources:
    - events
  verbs:
    - create
    - get
    - list
    - watch